server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    resolver 127.0.0.11 valid=10s ipv6=off;


    add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0" always;
    add_header Pragma "no-cache" always;
    expires -1;

    location = / {
        try_files /rediff-chat.html =404;
    }

    location /api/ {
        set $auth_service http://rediff_auth_service:8000;
        proxy_pass $auth_service;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Authorization $http_authorization;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
